language: node_js
node_js:
  - "stable"
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - node_modules
    - ~/.cache
install:
  - npm ci
script:
  - npm run test
  - npm start & npx wait-on http://localhost:3000
  - $(npm bin)/cypress run
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
